service: blog-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: ${env:STAGE, dev}
  region: ${env:AWS_DEFAULT_REGION, us-east-2}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:s3:::"
                - "Ref" : "ServerlessDeploymentBucket"
                - "/*"
  environment:
    DYNAMO_TRACKING_TABLE: ${ssm:${self:custom.SSM_PREFIX}/DYNAMO_TRACKING_TABLE}
  custom:
      SSM_PREFIX: /${env:STAGE}/${self:service}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hello:
    handler: bin/page-load
    events:
      - httpApi:
          path: /page-load
          method: get
  world:
    handler: bin/world
    events:
      - httpApi:
          path: /world
          method: get

#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
